CREATE TABLE post_images (
    id BIGSERIAL PRIMARY KEY,
    image_url TEXT NOT NULL,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);