// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (public_id, url, user_id, is_temp)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, url, user_id, is_temp, created_at
`

type CreateMediaParams struct {
	PublicID string
	Url      string
	UserID   int64
	IsTemp   bool
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.PublicID,
		arg.Url,
		arg.UserID,
		arg.IsTemp,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Url,
		&i.UserID,
		&i.IsTemp,
		&i.CreatedAt,
	)
	return i, err
}

const createPostImage = `-- name: CreatePostImage :exec
INSERT INTO post_images (image_url, media_id, post_id)
VALUES ($1, $2, $3)
`

type CreatePostImageParams struct {
	ImageUrl string
	MediaID  pgtype.Int8
	PostID   int64
}

func (q *Queries) CreatePostImage(ctx context.Context, arg CreatePostImageParams) error {
	_, err := q.db.Exec(ctx, createPostImage, arg.ImageUrl, arg.MediaID, arg.PostID)
	return err
}

const getUserTempMediaByIDs = `-- name: GetUserTempMediaByIDs :many
SELECT id, public_id, url, user_id, is_temp, created_at
FROM media
WHERE user_id = $1
  AND is_temp = TRUE
  AND id = ANY($2::bigint[])
`

type GetUserTempMediaByIDsParams struct {
	UserID  int64
	Column2 []int64
}

func (q *Queries) GetUserTempMediaByIDs(ctx context.Context, arg GetUserTempMediaByIDsParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, getUserTempMediaByIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Url,
			&i.UserID,
			&i.IsTemp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaPermanentByIDs = `-- name: MarkMediaPermanentByIDs :exec
UPDATE media
SET is_temp = FALSE
WHERE user_id = $1
  AND id = ANY($2::bigint[])
`

type MarkMediaPermanentByIDsParams struct {
	UserID  int64
	Column2 []int64
}

func (q *Queries) MarkMediaPermanentByIDs(ctx context.Context, arg MarkMediaPermanentByIDsParams) error {
	_, err := q.db.Exec(ctx, markMediaPermanentByIDs, arg.UserID, arg.Column2)
	return err
}
