// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
	PostStatusDeleted   PostStatus = "deleted"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus
	Valid      bool // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type College struct {
	ID           int64
	CollegeName  string
	CollegeEmail string
	State        string
	City         string
	CollegeType  pgtype.Text
	WebsiteUrl   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Comment struct {
	ID              int64
	Message         string
	PostID          int64
	UserID          int64
	ParentCommentID pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CommentLike struct {
	ID        int64
	CommentID int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type Event struct {
	ID          int64
	Title       string
	Description pgtype.Text
	Location    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	CreatedBy   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type EventImage struct {
	ID        int64
	EventID   int64
	ImageUrl  string
	CreatedAt pgtype.Timestamptz
}

type Medium struct {
	ID        int64
	PublicID  string
	Url       string
	UserID    int64
	IsTemp    bool
	CreatedAt pgtype.Timestamptz
}

type OtpRequest struct {
	ID          int64
	Email       string
	OtpHash     string
	ExpiresAt   pgtype.Timestamp
	Attempts    pgtype.Int4
	MaxAttempts pgtype.Int4
	Verified    pgtype.Bool
	CreatedAt   pgtype.Timestamp
}

type Post struct {
	ID        int64
	Title     pgtype.Text
	Body      pgtype.Text
	Status    NullPostStatus
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PostImage struct {
	ID        int64
	ImageUrl  string
	MediaID   pgtype.Int8
	PostID    int64
	CreatedAt pgtype.Timestamptz
}

type PostLike struct {
	ID        int64
	PostID    int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type PostTag struct {
	ID        int64
	PostID    int64
	UserID    int64
	TaggedBy  int64
	CreatedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        int64
	UserID    pgtype.Int8
	TokenHash string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID                 int64
	Username           string
	Email              string
	Name               pgtype.Text
	Dob                pgtype.Date
	ProfilePic         pgtype.Text
	CoverImage         pgtype.Text
	PasswordHash       string
	Course             pgtype.Text
	Yop                pgtype.Int4
	CollegeID          pgtype.Int8
	CollegeIDCard      pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	VerificationStatus pgtype.Text
	IsActive           pgtype.Bool
}

type UserFollow struct {
	ID              int64
	FollowerUserID  int64
	FollowingUserID int64
	CreatedAt       pgtype.Timestamptz
}
