// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPRequest = `-- name: CreateOTPRequest :exec
INSERT INTO otp_requests (email, otp_hash, expires_at, attempts, max_attempts, verified)
VALUES ($1, $2, $3, 0, $4, FALSE)
`

type CreateOTPRequestParams struct {
	Email       string
	OtpHash     string
	ExpiresAt   pgtype.Timestamp
	MaxAttempts pgtype.Int4
}

func (q *Queries) CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) error {
	_, err := q.db.Exec(ctx, createOTPRequest,
		arg.Email,
		arg.OtpHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	return err
}

const deleteOTPRequest = `-- name: DeleteOTPRequest :exec
DELETE FROM otp_requests
WHERE email = $1
`

func (q *Queries) DeleteOTPRequest(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOTPRequest, email)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, email, otp_hash, expires_at, attempts, max_attempts, verified, created_at
FROM otp_requests
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOTP(ctx context.Context, email string) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, email)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPRequestByEmail = `-- name: GetOTPRequestByEmail :one
SELECT id, email, otp_hash, expires_at, attempts, max_attempts, verified, created_at
FROM otp_requests
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOTPRequestByEmail(ctx context.Context, email string) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, getOTPRequestByEmail, email)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_requests
SET attempts = attempts + 1
WHERE email = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, email)
	return err
}

const markOTPAsVerified = `-- name: MarkOTPAsVerified :exec
UPDATE otp_requests
SET verified = TRUE
WHERE email = $1
`

func (q *Queries) MarkOTPAsVerified(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markOTPAsVerified, email)
	return err
}

const updateOTPRequest = `-- name: UpdateOTPRequest :exec
UPDATE otp_requests
SET attempts = $1,
    verified = $2,
    expires_at = $3,
    otp_hash = $4
WHERE email = $5
`

type UpdateOTPRequestParams struct {
	Attempts  pgtype.Int4
	Verified  pgtype.Bool
	ExpiresAt pgtype.Timestamp
	OtpHash   string
	Email     string
}

func (q *Queries) UpdateOTPRequest(ctx context.Context, arg UpdateOTPRequestParams) error {
	_, err := q.db.Exec(ctx, updateOTPRequest,
		arg.Attempts,
		arg.Verified,
		arg.ExpiresAt,
		arg.OtpHash,
		arg.Email,
	)
	return err
}
