// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_image.sql

package db

import (
	"context"
)

const getPostImageURLs = `-- name: GetPostImageURLs :many
SELECT image_url
FROM post_images
WHERE post_id = $1
`

func (q *Queries) GetPostImageURLs(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getPostImageURLs, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostImageURLsByPostIDs = `-- name: GetPostImageURLsByPostIDs :many
SELECT post_id, image_url
FROM post_images
WHERE post_id = ANY($1::bigint[])
ORDER BY post_id, id
`

type GetPostImageURLsByPostIDsRow struct {
	PostID   int64
	ImageUrl string
}

func (q *Queries) GetPostImageURLsByPostIDs(ctx context.Context, dollar_1 []int64) ([]GetPostImageURLsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getPostImageURLsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostImageURLsByPostIDsRow
	for rows.Next() {
		var i GetPostImageURLsByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
