// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, body, status, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, body, status, user_id, created_at, updated_at
`

type CreatePostParams struct {
	Title  pgtype.Text
	Body   pgtype.Text
	Status NullPostStatus
	UserID int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.UserID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostImagesBulk = `-- name: CreatePostImagesBulk :exec
INSERT INTO post_images (post_id, media_id, image_url)
SELECT $1, m.id, m.url
FROM media m
WHERE m.id = ANY($2::bigint[])
`

type CreatePostImagesBulkParams struct {
	PostID  int64
	Column2 []int64
}

func (q *Queries) CreatePostImagesBulk(ctx context.Context, arg CreatePostImagesBulkParams) error {
	_, err := q.db.Exec(ctx, createPostImagesBulk, arg.PostID, arg.Column2)
	return err
}

const createPostTag = `-- name: CreatePostTag :exec
INSERT INTO post_tags (post_id, user_id, tagged_by)
VALUES ($1, $2, $3)
`

type CreatePostTagParams struct {
	PostID   int64
	UserID   int64
	TaggedBy int64
}

func (q *Queries) CreatePostTag(ctx context.Context, arg CreatePostTagParams) error {
	_, err := q.db.Exec(ctx, createPostTag, arg.PostID, arg.UserID, arg.TaggedBy)
	return err
}

const createPostTagsBulk = `-- name: CreatePostTagsBulk :exec
INSERT INTO post_tags (post_id, user_id, tagged_by)
SELECT $1, unnest($2::bigint[]), $3
ON CONFLICT DO NOTHING
`

type CreatePostTagsBulkParams struct {
	PostID   int64
	Column2  []int64
	TaggedBy int64
}

func (q *Queries) CreatePostTagsBulk(ctx context.Context, arg CreatePostTagsBulkParams) error {
	_, err := q.db.Exec(ctx, createPostTagsBulk, arg.PostID, arg.Column2, arg.TaggedBy)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, body, status, user_id, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
