// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_image.sql

package db

import (
	"context"
)

const getPostImageURLs = `-- name: GetPostImageURLs :many
SELECT image_url
FROM post_images
WHERE post_id = $1
`

func (q *Queries) GetPostImageURLs(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getPostImageURLs, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
