// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_tag.sql

package db

import (
	"context"
)

const getTaggedUserIDs = `-- name: GetTaggedUserIDs :many
SELECT user_id
FROM post_tags
WHERE post_id = $1
`

func (q *Queries) GetTaggedUserIDs(ctx context.Context, postID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getTaggedUserIDs, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
