// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.Int8
	TokenHash string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, email, name, password_hash, course, yop)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	Username     string
	Email        string
	Name         pgtype.Text
	PasswordHash string
	Course       pgtype.Text
	Yop          pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Course,
		arg.Yop,
	)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, name, dob, profile_pic, cover_image, password_hash, course, yop, college_id, college_id_card, created_at, updated_at, verification_status, is_active FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Dob,
		&i.ProfilePic,
		&i.CoverImage,
		&i.PasswordHash,
		&i.Course,
		&i.Yop,
		&i.CollegeID,
		&i.CollegeIDCard,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, name, dob, profile_pic, cover_image, password_hash, course, yop, college_id, college_id_card, created_at, updated_at, verification_status, is_active FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Dob,
		&i.ProfilePic,
		&i.CoverImage,
		&i.PasswordHash,
		&i.Course,
		&i.Yop,
		&i.CollegeID,
		&i.CollegeIDCard,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, name, dob, profile_pic, cover_image, password_hash, course, yop, college_id, college_id_card, created_at, updated_at, verification_status, is_active FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Dob,
		&i.ProfilePic,
		&i.CoverImage,
		&i.PasswordHash,
		&i.Course,
		&i.Yop,
		&i.CollegeID,
		&i.CollegeIDCard,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
		&i.IsActive,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, name, dob, profile_pic, cover_image, password_hash, course, yop, college_id, college_id_card, created_at, updated_at, verification_status, is_active FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Dob,
		&i.ProfilePic,
		&i.CoverImage,
		&i.PasswordHash,
		&i.Course,
		&i.Yop,
		&i.CollegeID,
		&i.CollegeIDCard,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationStatus,
		&i.IsActive,
	)
	return i, err
}
